### ISSUE TITLE
Requirement spiral version 1.1.0 is not available through PyPI

### ISSUE THREAD

**Issue by mlanicaputo** [nalmadi/Namesake#6]
[spiral](https://pypi.org/project/spiral/), a requirement of Namesake, is not available through PyPI. Running `pip install -r requirements.txt` will not install the package, since the specified requirement is version 1.1.0 but the most recent version available on PyPI is 0.14.1.0. I was able to get around this problem by cloning the [GitHub repository](https://github.com/casics/spiral) and manually installing it into my virtual environment but that's not a sustainable fix.

The Spiral setup documentation recommends the following command for installing the latest version of spiral: `sudo pip3 install git+https://github.com/casics/spiral.git`.

**Comment by nalmadi** [comment]
I think there's another python package with the same name, and you found the correct project: [https://github.com/casics/spiral](https://github.com/casics/spiral)

The following command should work:
sudo pip3 install git+https://github.com/casics/spiral.git
